yunjee/search/urls.py
from django.urls import path
from . import views

app_name = 'search'

urlpatterns = [
path('', views.searchResult, name='searchResult'),
]

yunjee/yunjee_p/urls.py
from django.contrib import admin
from django.urls import path, include
import writing.views
import login.views
import review.views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', writing.views.home, name = 'home'),
    path('blog/<int:blog_id>', writing.views.detail, name = 'detail'),
    path('create/<int:step>', writing.views.create, name = 'create'),
    path('delete/', writing.views.delete, name = 'delete'),
    path('signup/', login.views.signup, name='signup'),
    path('login/', login.views.login, name='login'),
    path('logout/', login.views.logout, name='logout'),
    path('accounts/', include('allauth.urls')),
    path('like/<int:blog_id>',writing.views.blog_like, name="like"),
    path('search/', include('search.urls'), name='search'),
    path('profile/',login.views.profile, name="profile"),
    path('profile_update/',login.views.profile_update),
    path('review/', review.views.review, name = 'review'),
    path('delete_review/<int:review_id>', review.views.delete_review, name='delete_review'),
    path('download/<int:blog_id>', writing.views.file_download, name='download'),
    ] + static(settings. MEDIA_URL, document_root=settings.MEDIA_ROOT)

yunjee/yunjee_p/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous">
    </script>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">윤지와 아이들</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home' %}">Home<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'create' %}">글쓰기</a>
                </li>
            </ul>
            <!-- 검색 창 구현 -->
            <form class="form-inline my-2 my-lg-0" action="{% url 'search:searchResult' %}" method="get">
                {% csrf_token %}
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit"><i class="fad fa-search"></i></button>
            </form>
        </div>
    </nav>

    {% block content %}

    {% endblock %}

</body>

</html>